# Generated by Django 4.0.4 on 2022-10-01 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_order_id_alter_orderitem_id_alter_product_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='deliveredAt',
            new_name='delivered_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='isDelivered',
            new_name='is_delivered',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='isPaid',
            new_name='is_paid',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='paidAt',
            new_name='paid_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='paymentMethod',
            new_name='payment_method',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shippingPrice',
            new_name='shipping_price',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='taxPrice',
            new_name='tax_price',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='totalPrice',
            new_name='total_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='countInStock',
            new_name='count_in_stock',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='numReviews',
            new_name='num_reviews',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='postalCode',
            new_name='postal_code',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='shippingPrice',
            new_name='shipping_price',
        ),
    ]
